// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ProxyCandidate struct {
	Ip           string
	Port         int32
	Protocol     string
	ProcessedAt  pgtype.Timestamp
	TestedAt     pgtype.Timestamp
	AllowRetryAt pgtype.Timestamp
	TestError    pgtype.Text
}

type ProxyInfo struct {
	Ip                  string
	Port                int32
	Protocol            string
	Delay               pgtype.Interval
	TestedAt            pgtype.Timestamp
	Websocket           pgtype.Bool
	Anonymity           pgtype.Bool
	ItemFetch           pgtype.Bool
	FetchErrorCount     pgtype.Int4
	WebsocketErrorCount pgtype.Int4
}
